name: Tim Keller
pygments: true
permalink: /:year/:month/:day/:title/
markdown: kramdown
paginate: 5

prose:
  rooturl: '_posts'
  siteurl: 'http://timkeller.me/'
  #relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'assets'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"